export const POST_WEDDING_TASKS: { timeframe: string; task: string; category: string }[] = [
  { timeframe: 'After the Big Day', task: 'Send thank-you cards to guests', category: 'Guests' },
  { timeframe: 'After the Big Day', task: 'Review and rate your vendors', category: 'Vendors' },
  { timeframe: 'After the Big Day', task: 'Order prints and photo album from photographer', category: 'Vendors' },
  { timeframe: 'After the Big Day', task: 'Preserve wedding attire (dress, suit)', category: 'Attire' },
  { timeframe: 'After the Big Day', task: 'Handle change-of-name paperwork (if applicable)', category: 'Planning' },
  { timeframe: 'After the Big Day', task: 'Close out final vendor payments', category: 'Budget' },
];

export const DEFAULT_CHECKLIST_TASKS: { timeframe: string; task: string; category: string }[] = [
  { timeframe: '18+ Months', task: 'Set your overall wedding budget', category: 'Planning' },
  { timeframe: '18+ Months', task: 'Discuss vision and priorities with partner', category: 'Planning' },
  { timeframe: '18+ Months', task: 'Research and book venue', category: 'Venue' },
  { timeframe: '18+ Months', task: 'Set a wedding date', category: 'Planning' },
  { timeframe: '18+ Months', task: 'Create a preliminary guest list', category: 'Guests' },
  { timeframe: '12 Months', task: 'Book wedding photographer', category: 'Vendors' },
  { timeframe: '12 Months', task: 'Book videographer', category: 'Vendors' },
  { timeframe: '12 Months', task: 'Book caterer', category: 'Vendors' },
  { timeframe: '12 Months', task: 'Book DJ or band', category: 'Vendors' },
  { timeframe: '12 Months', task: 'Choose and ask bridal party', category: 'Bridal Party' },
  { timeframe: '12 Months', task: 'Start dress shopping', category: 'Attire' },
  { timeframe: '9 Months', task: 'Order wedding dress', category: 'Attire' },
  { timeframe: '9 Months', task: 'Book florist', category: 'Vendors' },
  { timeframe: '9 Months', task: 'Book officiant', category: 'Vendors' },
  { timeframe: '9 Months', task: 'Plan honeymoon and book travel', category: 'Honeymoon' },
  { timeframe: '9 Months', task: 'Create wedding website', category: 'Planning' },
  { timeframe: '6 Months', task: 'Send save-the-dates', category: 'Guests' },
  { timeframe: '6 Months', task: 'Book hair and makeup', category: 'Vendors' },
  { timeframe: '6 Months', task: 'Register for wedding gifts', category: 'Gifts' },
  { timeframe: '6 Months', task: 'Plan ceremony details', category: 'Ceremony' },
  { timeframe: '6 Months', task: 'Choose bridesmaids dresses', category: 'Attire' },
  { timeframe: '3 Months', task: 'Send wedding invitations', category: 'Guests' },
  { timeframe: '3 Months', task: 'Order wedding cake', category: 'Vendors' },
  { timeframe: '3 Months', task: 'Schedule dress fittings', category: 'Attire' },
  { timeframe: '3 Months', task: 'Book transportation', category: 'Vendors' },
  { timeframe: '3 Months', task: 'Plan rehearsal dinner', category: 'Events' },
  { timeframe: '1 Month', task: 'Confirm all vendors', category: 'Vendors' },
  { timeframe: '1 Month', task: 'Finalize seating chart', category: 'Guests' },
  { timeframe: '1 Month', task: 'Final dress fitting', category: 'Attire' },
  { timeframe: '1 Month', task: 'Create wedding day timeline', category: 'Planning' },
  { timeframe: '1 Month', task: 'Prepare vendor payments', category: 'Budget' },
  { timeframe: '2 Weeks', task: 'Send final guest count to caterer', category: 'Vendors' },
  { timeframe: '2 Weeks', task: 'Confirm honeymoon reservations', category: 'Honeymoon' },
  { timeframe: '2 Weeks', task: 'Break in wedding shoes', category: 'Attire' },
  { timeframe: '2 Weeks', task: 'Prepare wedding day emergency kit', category: 'Planning' },
  { timeframe: '1 Week', task: 'Confirm all vendor arrival times', category: 'Vendors' },
  { timeframe: '1 Week', task: 'Prepare ceremony programs', category: 'Ceremony' },
  { timeframe: '1 Week', task: 'Prepare tips and payments', category: 'Budget' },
  { timeframe: '1 Week', task: 'Rehearsal dinner', category: 'Events' },
  { timeframe: 'Day Before', task: 'Wedding rehearsal', category: 'Ceremony' },
  { timeframe: 'Day Before', task: 'Confirm transportation details', category: 'Vendors' },
  { timeframe: 'Day Before', task: 'Pack wedding day bag', category: 'Planning' },
  { timeframe: 'Day Before', task: 'Get a good night sleep!', category: 'Self-Care' },
  { timeframe: 'Wedding Day', task: 'Hair and makeup', category: 'Attire' },
  { timeframe: 'Wedding Day', task: 'Photographer arrives for prep', category: 'Vendors' },
  { timeframe: 'Wedding Day', task: 'Get dressed with bridal party', category: 'Attire' },
  { timeframe: 'Wedding Day', task: 'Ceremony', category: 'Ceremony' },
  { timeframe: 'Wedding Day', task: 'Reception', category: 'Reception' },
];
