export interface RouteSeo {
  title: string;
  description: string;
  canonical: string;
  ogImage?: string;
  ogType: string;
  jsonLd?: object;
  noindex?: boolean;
  excludeFromSitemap?: boolean;
  priority?: number;
  changefreq?: string;
}

const SITE_URL = 'https://weddingplanner.day';
const DEFAULT_OG = '/og-image.jpg';

const faqJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: [
    { '@type': 'Question', name: 'What is Vow?', acceptedAnswer: { '@type': 'Answer', text: 'Vow is an all-in-one wedding planning app with checklist, budget tracker, guest list, seating chart, vendor manager, and day-of timeline.' } },
    { '@type': 'Question', name: 'Is Vow free?', acceptedAnswer: { '@type': 'Answer', text: 'Yes. Vow is free to start with no credit card. Pro is $15/month or $99/year for unlimited guests, seating chart, and collaboration.' } },
    { '@type': 'Question', name: 'Can my partner and I plan together?', acceptedAnswer: { '@type': 'Answer', text: 'Yes, with Vow Pro you can invite your partner to co-plan in real time.' } },
    { '@type': 'Question', name: 'Does Vow work on my phone?', acceptedAnswer: { '@type': 'Answer', text: 'Yes. Vow is fully responsive and works on any modern smartphone browser.' } },
  ],
};

const appJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'SoftwareApplication',
  name: 'Vow Wedding Planner',
  url: SITE_URL,
  description: 'All-in-one wedding planning app with checklist, budget tracker, guest list, seating chart, and vendor manager.',
  applicationCategory: 'LifestyleApplication',
  operatingSystem: 'Web',
  offers: [
    { '@type': 'Offer', price: '0', priceCurrency: 'USD', name: 'Free plan' },
    { '@type': 'Offer', price: '15', priceCurrency: 'USD', name: 'Pro plan monthly', billingIncrement: 'P1M' },
    { '@type': 'Offer', price: '99', priceCurrency: 'USD', name: 'Pro plan annual', billingIncrement: 'P1Y' },
  ],
};

function breadcrumb(items: { name: string; url: string }[]) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: items.map((item, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: item.name,
      item: `${SITE_URL}${item.url}`,
    })),
  };
}

function articleJsonLd(headline: string, datePublished: string, author: string, url: string) {
  return {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline,
    datePublished,
    author: { '@type': 'Organization', name: author },
    publisher: { '@type': 'Organization', name: 'Vow Wedding Planner' },
    mainEntityOfPage: `${SITE_URL}${url}`,
  };
}

export const ROUTE_SEO: Record<string, RouteSeo> = {
  '/': {
    title: 'Vow — Free Wedding Planning App: Checklist & Budget',
    description: 'Plan your entire wedding in one place. Free checklist, budget tracker, guest list, seating chart, vendor manager, and day-of timeline.',
    canonical: '/',
    ogType: 'website',
    jsonLd: appJsonLd,
    priority: 1.0,
    changefreq: 'weekly',
  },
  '/for-planners': {
    title: 'Wedding Planner Software — Manage Clients | Vow',
    description: 'Professional wedding planner tools are coming soon to Vow. Join the waitlist for early access to multi-client management, branded PDFs, and more.',
    canonical: '/for-planners',
    ogType: 'website',
    jsonLd: breadcrumb([{ name: 'Home', url: '/' }, { name: 'For Planners', url: '/for-planners' }]),
    priority: 0.8,
    changefreq: 'monthly',
  },
  '/blog': {
    title: 'Wedding Planning Blog — Tips & Advice | Vow',
    description: 'Expert wedding planning tips, timelines, budget advice, guest list etiquette, and vendor guides to help you plan your wedding.',
    canonical: '/blog',
    ogType: 'website',
    jsonLd: breadcrumb([{ name: 'Home', url: '/' }, { name: 'Blog', url: '/blog' }]),
    priority: 0.7,
    changefreq: 'weekly',
  },
  '/blog/wedding-planning-timeline': {
    title: 'Complete Wedding Planning Timeline Month-by-Month',
    description: 'Your complete wedding planning timeline from 18 months out to your wedding day. Every task organized by month so you never miss a step.',
    canonical: '/blog/wedding-planning-timeline',
    ogType: 'article',
    jsonLd: [
      articleJsonLd('The Complete Wedding Planning Timeline', '2026-01-15', 'Vow Editorial Team', '/blog/wedding-planning-timeline'),
      breadcrumb([{ name: 'Home', url: '/' }, { name: 'Blog', url: '/blog' }, { name: 'Planning Timeline', url: '/blog/wedding-planning-timeline' }]),
    ],
    priority: 0.6,
    changefreq: 'monthly',
  },
  '/blog/wedding-budget-tips': {
    title: '10 Ways to Stretch Your Wedding Budget | Vow',
    description: 'Smart strategies to save money on your wedding without sacrificing style. Real tips on venues, catering, flowers, and more.',
    canonical: '/blog/wedding-budget-tips',
    ogType: 'article',
    jsonLd: [
      articleJsonLd('10 Ways to Stretch Your Wedding Budget', '2026-01-22', 'Vow Editorial Team', '/blog/wedding-budget-tips'),
      breadcrumb([{ name: 'Home', url: '/' }, { name: 'Blog', url: '/blog' }, { name: 'Budget Tips', url: '/blog/wedding-budget-tips' }]),
    ],
    priority: 0.6,
    changefreq: 'monthly',
  },
  '/blog/guest-list-etiquette': {
    title: 'Wedding Guest List Etiquette: Who to Invite | Vow',
    description: 'Navigate plus-ones, distant relatives, and coworkers. Practical guest list etiquette tips for every wedding situation.',
    canonical: '/blog/guest-list-etiquette',
    ogType: 'article',
    jsonLd: [
      articleJsonLd('Guest List Etiquette: Who to Invite and How to Handle the Hard Cases', '2026-02-03', 'Vow Editorial Team', '/blog/guest-list-etiquette'),
      breadcrumb([{ name: 'Home', url: '/' }, { name: 'Blog', url: '/blog' }, { name: 'Guest List Etiquette', url: '/blog/guest-list-etiquette' }]),
    ],
    priority: 0.6,
    changefreq: 'monthly',
  },
  '/blog/vendor-tips': {
    title: 'How to Interview & Book Wedding Vendors | Vow',
    description: 'The essential questions to ask every wedding vendor before signing a contract. Tips for photographers, caterers, florists, and DJs.',
    canonical: '/blog/vendor-tips',
    ogType: 'article',
    jsonLd: [
      articleJsonLd('How to Interview and Book Wedding Vendors', '2026-02-18', 'Vow Editorial Team', '/blog/vendor-tips'),
      breadcrumb([{ name: 'Home', url: '/' }, { name: 'Blog', url: '/blog' }, { name: 'Vendor Tips', url: '/blog/vendor-tips' }]),
    ],
    priority: 0.6,
    changefreq: 'monthly',
  },
  '/blog/wedding-day-timeline': {
    title: 'Perfect Wedding Day Timeline Template & Tips | Vow',
    description: 'How to structure your wedding day from getting ready to last dance. A minute-by-minute timeline template to minimize stress.',
    canonical: '/blog/wedding-day-timeline',
    ogType: 'article',
    jsonLd: [
      articleJsonLd('Building the Perfect Wedding Day Timeline', '2026-03-05', 'Vow Editorial Team', '/blog/wedding-day-timeline'),
      breadcrumb([{ name: 'Home', url: '/' }, { name: 'Blog', url: '/blog' }, { name: 'Day Timeline', url: '/blog/wedding-day-timeline' }]),
    ],
    priority: 0.6,
    changefreq: 'monthly',
  },
  '/blog/honeymoon-planning': {
    title: 'Honeymoon Planning Guide: Destinations & Tips | Vow',
    description: 'From destination selection to packing lists, plan your perfect honeymoon with this comprehensive guide for newlyweds.',
    canonical: '/blog/honeymoon-planning',
    ogType: 'article',
    jsonLd: [
      articleJsonLd('Honeymoon Planning 101', '2026-03-20', 'Vow Editorial Team', '/blog/honeymoon-planning'),
      breadcrumb([{ name: 'Home', url: '/' }, { name: 'Blog', url: '/blog' }, { name: 'Honeymoon Planning', url: '/blog/honeymoon-planning' }]),
    ],
    priority: 0.6,
    changefreq: 'monthly',
  },
  '/blog/wedding-catering-service-charge-vs-gratuity': {
    title: 'Service Charge vs Gratuity on a Wedding Catering Quote',
    description: 'A 22% service charge is not a tip. See how service charge, gratuity and sales tax stack on a real catering quote — and what to ask before signing.',
    canonical: '/blog/wedding-catering-service-charge-vs-gratuity',
    ogType: 'article',
    jsonLd: [
      articleJsonLd('Service Charge vs Gratuity on a Wedding Catering Quote', '2026-08-15', 'Vow Editorial Team', '/blog/wedding-catering-service-charge-vs-gratuity'),
      breadcrumb([{ name: 'Home', url: '/' }, { name: 'Blog', url: '/blog' }, { name: 'Catering Service Charge vs Gratuity', url: '/blog/wedding-catering-service-charge-vs-gratuity' }]),
    ],
    priority: 0.6,
    changefreq: 'monthly',
  },
  '/blog/wedding-day-timeline-4pm-ceremony': {
    title: 'Wedding Day Timeline for a 4pm Ceremony (Hour by Hour)',
    description: 'Two complete 4pm timelines — with and without a first look — plus how to shift every block when your sunset time is different.',
    canonical: '/blog/wedding-day-timeline-4pm-ceremony',
    ogType: 'article',
    jsonLd: [
      articleJsonLd('Wedding Day Timeline for a 4pm Ceremony (Hour by Hour)', '2026-08-16', 'Vow Editorial Team', '/blog/wedding-day-timeline-4pm-ceremony'),
      breadcrumb([{ name: 'Home', url: '/' }, { name: 'Blog', url: '/blog' }, { name: '4pm Ceremony Timeline', url: '/blog/wedding-day-timeline-4pm-ceremony' }]),
    ],
    priority: 0.6,
    changefreq: 'monthly',
  },
  '/blog/what-time-to-start-wedding-ceremony': {
    title: 'What Time to Start Your Wedding Ceremony (Sunset Math)',
    description: 'Pick a ceremony time by working backward from sunset. The formula, worked examples by season, and the reception-length tradeoff.',
    canonical: '/blog/what-time-to-start-wedding-ceremony',
    ogType: 'article',
    jsonLd: [
      articleJsonLd('What Time to Start Your Wedding Ceremony (Sunset Math)', '2026-08-17', 'Vow Editorial Team', '/blog/what-time-to-start-wedding-ceremony'),
      breadcrumb([{ name: 'Home', url: '/' }, { name: 'Blog', url: '/blog' }, { name: 'Ceremony Start Time', url: '/blog/what-time-to-start-wedding-ceremony' }]),
    ],
    priority: 0.6,
    changefreq: 'monthly',
  },
  '/blog/wedding-b-list-invitation-timing': {
    title: 'Wedding B-List Timing: When to Send Round Two',
    description: 'The exact send dates that keep a B-list invisible, how to set an early RSVP date to make room, and the mistakes that give it away.',
    canonical: '/blog/wedding-b-list-invitation-timing',
    ogType: 'article',
    jsonLd: [
      articleJsonLd('Wedding B-List Timing: When to Send Round Two', '2026-08-18', 'Vow Editorial Team', '/blog/wedding-b-list-invitation-timing'),
      breadcrumb([{ name: 'Home', url: '/' }, { name: 'Blog', url: '/blog' }, { name: 'B-List Timing', url: '/blog/wedding-b-list-invitation-timing' }]),
    ],
    priority: 0.6,
    changefreq: 'monthly',
  },
  '/blog/do-you-have-to-feed-wedding-vendors': {
    title: 'Do You Have to Feed Your Wedding Vendors?',
    description: 'Which vendors get a meal, how to count them, what a vendor meal costs versus a guest plate, and where the requirement hides in your contract.',
    canonical: '/blog/do-you-have-to-feed-wedding-vendors',
    ogType: 'article',
    jsonLd: [
      articleJsonLd('Do You Have to Feed Your Wedding Vendors?', '2026-08-19', 'Vow Editorial Team', '/blog/do-you-have-to-feed-wedding-vendors'),
      breadcrumb([{ name: 'Home', url: '/' }, { name: 'Blog', url: '/blog' }, { name: 'Feeding Vendors', url: '/blog/do-you-have-to-feed-wedding-vendors' }]),
    ],
    priority: 0.6,
    changefreq: 'monthly',
  },
  '/blog/kids-table-wedding-reception': {
    title: 'Kids Table at a Wedding: Ages, Size and Placement',
    description: 'What ages belong at a kids table, how many children make it worth doing, where to place it, and when to seat kids with parents instead.',
    canonical: '/blog/kids-table-wedding-reception',
    ogType: 'article',
    jsonLd: [
      articleJsonLd('Kids Table at a Wedding: Ages, Size and Placement', '2026-08-20', 'Vow Editorial Team', '/blog/kids-table-wedding-reception'),
      breadcrumb([{ name: 'Home', url: '/' }, { name: 'Blog', url: '/blog' }, { name: 'Kids Table', url: '/blog/kids-table-wedding-reception' }]),
    ],
    priority: 0.6,
    changefreq: 'monthly',
  },
  '/blog/how-many-guests-per-table': {
    title: 'How Many Guests Fit Per Wedding Table (Every Size)',
    description: 'Seating capacity for 60 and 72 inch rounds and every banquet length, the comfortable vs maximum numbers, and how many tables you actually need.',
    canonical: '/blog/how-many-guests-per-table',
    ogType: 'article',
    jsonLd: [
      articleJsonLd('How Many Guests Fit Per Wedding Table (Every Size)', '2026-08-21', 'Vow Editorial Team', '/blog/how-many-guests-per-table'),
      breadcrumb([{ name: 'Home', url: '/' }, { name: 'Blog', url: '/blog' }, { name: 'Guests Per Table', url: '/blog/how-many-guests-per-table' }]),
    ],
    priority: 0.6,
    changefreq: 'monthly',
  },
  '/blog/how-to-seat-divorced-parents': {
    title: 'How to Seat Divorced Parents at Your Wedding',
    description: 'Ceremony and reception seating arrangements for divorced parents and step-parents, including the amicable, tense and estranged versions.',
    canonical: '/blog/how-to-seat-divorced-parents',
    ogType: 'article',
    jsonLd: [
      articleJsonLd('How to Seat Divorced Parents at Your Wedding', '2026-08-22', 'Vow Editorial Team', '/blog/how-to-seat-divorced-parents'),
      breadcrumb([{ name: 'Home', url: '/' }, { name: 'Blog', url: '/blog' }, { name: 'Seating Divorced Parents', url: '/blog/how-to-seat-divorced-parents' }]),
    ],
    priority: 0.6,
    changefreq: 'monthly',
  },
  '/blog/hidden-wedding-costs-forgotten': {
    title: 'Hidden Wedding Costs Couples Forget to Budget For',
    description: 'Twenty-three real costs that show up after you have booked — with typical dollar amounts and the month each one usually hits your budget.',
    canonical: '/blog/hidden-wedding-costs-forgotten',
    ogType: 'article',
    jsonLd: [
      articleJsonLd('Hidden Wedding Costs Couples Forget to Budget For', '2026-08-23', 'Vow Editorial Team', '/blog/hidden-wedding-costs-forgotten'),
      breadcrumb([{ name: 'Home', url: '/' }, { name: 'Blog', url: '/blog' }, { name: 'Hidden Wedding Costs', url: '/blog/hidden-wedding-costs-forgotten' }]),
    ],
    priority: 0.6,
    changefreq: 'monthly',
  },
  '/blog/25000-wedding-budget-100-guests': {
    title: '$25,000 Wedding Budget for 100 Guests: Real Breakdown',
    description: 'A line-by-line $25,000 wedding budget for 100 guests, including the three categories couples always underfund and where the money really goes.',
    canonical: '/blog/25000-wedding-budget-100-guests',
    ogType: 'article',
    jsonLd: [
      articleJsonLd('$25,000 Wedding Budget for 100 Guests: Real Breakdown', '2026-08-24', 'Vow Editorial Team', '/blog/25000-wedding-budget-100-guests'),
      breadcrumb([{ name: 'Home', url: '/' }, { name: 'Blog', url: '/blog' }, { name: '$25K Budget Breakdown', url: '/blog/25000-wedding-budget-100-guests' }]),
    ],
    priority: 0.6,
    changefreq: 'monthly',
  },
  '/blog/cost-per-wedding-guest': {
    title: 'How Much Each Wedding Guest Actually Costs You',
    description: 'Your true cost per guest is not the catering quote. Add up the eight per-head line items and see what cutting 20 people really saves.',
    canonical: '/blog/cost-per-wedding-guest',
    ogType: 'article',
    jsonLd: [
      articleJsonLd('How Much Each Wedding Guest Actually Costs You', '2026-08-25', 'Vow Editorial Team', '/blog/cost-per-wedding-guest'),
      breadcrumb([{ name: 'Home', url: '/' }, { name: 'Blog', url: '/blog' }, { name: 'Cost Per Guest', url: '/blog/cost-per-wedding-guest' }]),
    ],
    priority: 0.6,
    changefreq: 'monthly',
  },
  '/blog/percentage-wedding-guests-decline': {
    title: 'What Percent of Wedding Guests Actually Decline?',
    description: 'Decline rates by guest type, distance and season — plus how to invite the right number so you land on your target headcount.',
    canonical: '/blog/percentage-wedding-guests-decline',
    ogType: 'article',
    jsonLd: [
      articleJsonLd('What Percent of Wedding Guests Actually Decline?', '2026-08-26', 'Vow Editorial Team', '/blog/percentage-wedding-guests-decline'),
      breadcrumb([{ name: 'Home', url: '/' }, { name: 'Blog', url: '/blog' }, { name: 'Guest Decline Rate', url: '/blog/percentage-wedding-guests-decline' }]),
    ],
    priority: 0.6,
    changefreq: 'monthly',
  },
  '/blog/guests-didnt-rsvp-what-to-do': {
    title: 'Guests Didn\'t RSVP by the Deadline? Do This.',
    description: 'A day-by-day follow-up sequence with copy-paste texts and call scripts, plus how to count non-responders for your final catering number.',
    canonical: '/blog/guests-didnt-rsvp-what-to-do',
    ogType: 'article',
    jsonLd: [
      articleJsonLd('Guests Didn\'t RSVP by the Deadline? Do This.', '2026-08-27', 'Vow Editorial Team', '/blog/guests-didnt-rsvp-what-to-do'),
      breadcrumb([{ name: 'Home', url: '/' }, { name: 'Blog', url: '/blog' }, { name: 'Guests Didn\'t RSVP', url: '/blog/guests-didnt-rsvp-what-to-do' }]),
    ],
    priority: 0.6,
    changefreq: 'monthly',
  },
  '/blog/how-to-cut-wedding-guest-list': {
    title: 'How to Cut Your Wedding Guest List Without Drama',
    description: 'Five cut rules that apply consistently, how to handle parents\' add-ons, and what to say when someone asks why they were not invited.',
    canonical: '/blog/how-to-cut-wedding-guest-list',
    ogType: 'article',
    jsonLd: [
      articleJsonLd('How to Cut Your Wedding Guest List Without Drama', '2026-08-28', 'Vow Editorial Team', '/blog/how-to-cut-wedding-guest-list'),
      breadcrumb([{ name: 'Home', url: '/' }, { name: 'Blog', url: '/blog' }, { name: 'Cut Guest List', url: '/blog/how-to-cut-wedding-guest-list' }]),
    ],
    priority: 0.6,
    changefreq: 'monthly',
  },
  '/blog/wedding-checklist-final-month': {
    title: 'Wedding Checklist: The Final Month, Week by Week',
    description: 'A week-by-week checklist for the last 30 days — final counts, payments, deliverables and the handoffs most couples forget until it is too late.',
    canonical: '/blog/wedding-checklist-final-month',
    ogType: 'article',
    jsonLd: [
      articleJsonLd('Wedding Checklist: The Final Month, Week by Week', '2026-08-29', 'Vow Editorial Team', '/blog/wedding-checklist-final-month'),
      breadcrumb([{ name: 'Home', url: '/' }, { name: 'Blog', url: '/blog' }, { name: 'Final Month Checklist', url: '/blog/wedding-checklist-final-month' }]),
    ],
    priority: 0.6,
    changefreq: 'monthly',
  },
  '/blog/wedding-vendor-contract-red-flags': {
    title: 'Wedding Vendor Contract Red Flags to Check Before You Sign',
    description: 'Twelve clauses that should stop you signing — cancellation, substitution, force majeure, overtime — with the exact language to ask for instead.',
    canonical: '/blog/wedding-vendor-contract-red-flags',
    ogType: 'article',
    jsonLd: [
      articleJsonLd('Wedding Vendor Contract Red Flags to Check Before You Sign', '2026-08-30', 'Vow Editorial Team', '/blog/wedding-vendor-contract-red-flags'),
      breadcrumb([{ name: 'Home', url: '/' }, { name: 'Blog', url: '/blog' }, { name: 'Contract Red Flags', url: '/blog/wedding-vendor-contract-red-flags' }]),
    ],
    priority: 0.6,
    changefreq: 'monthly',
  },
  '/blog/wedding-timeline-buffer-time': {
    title: 'How Much Buffer Time a Wedding Timeline Needs',
    description: 'Where wedding days actually lose time, how many minutes to pad each block, and the four points where a delay cascades through everything after.',
    canonical: '/blog/wedding-timeline-buffer-time',
    ogType: 'article',
    jsonLd: [
      articleJsonLd('How Much Buffer Time a Wedding Timeline Needs', '2026-08-31', 'Vow Editorial Team', '/blog/wedding-timeline-buffer-time'),
      breadcrumb([{ name: 'Home', url: '/' }, { name: 'Blog', url: '/blog' }, { name: 'Timeline Buffer Time', url: '/blog/wedding-timeline-buffer-time' }]),
    ],
    priority: 0.6,
    changefreq: 'monthly',
  },
  '/blog/head-table-vs-sweetheart-table': {
    title: 'Head Table vs Sweetheart Table: How to Decide',
    description: 'The real tradeoffs — dates, floor space, cost and photos — plus what to do with the wedding party if you choose a sweetheart table.',
    canonical: '/blog/head-table-vs-sweetheart-table',
    ogType: 'article',
    jsonLd: [
      articleJsonLd('Head Table vs Sweetheart Table: How to Decide', '2026-09-01', 'Vow Editorial Team', '/blog/head-table-vs-sweetheart-table'),
      breadcrumb([{ name: 'Home', url: '/' }, { name: 'Blog', url: '/blog' }, { name: 'Head Table vs Sweetheart Table', url: '/blog/head-table-vs-sweetheart-table' }]),
    ],
    priority: 0.6,
    changefreq: 'monthly',
  },
  '/blog/wedding-vendor-payment-schedule': {
    title: 'When Wedding Vendor Final Payments Are Due',
    description: 'Typical deposit and final-payment timing by vendor type, why so much lands in the last 30 days, and how to plan cash flow around it.',
    canonical: '/blog/wedding-vendor-payment-schedule',
    ogType: 'article',
    jsonLd: [
      articleJsonLd('When Wedding Vendor Final Payments Are Due', '2026-09-02', 'Vow Editorial Team', '/blog/wedding-vendor-payment-schedule'),
      breadcrumb([{ name: 'Home', url: '/' }, { name: 'Blog', url: '/blog' }, { name: 'Vendor Payment Schedule', url: '/blog/wedding-vendor-payment-schedule' }]),
    ],
    priority: 0.6,
    changefreq: 'monthly',
  },
  '/blog/who-gets-a-plus-one-wedding': {
    title: 'Who Gets a Plus-One at Your Wedding? Clear Rules',
    description: 'A consistent plus-one policy that survives scrutiny, envelope wording that makes it unambiguous, and how to handle the people who ask anyway.',
    canonical: '/blog/who-gets-a-plus-one-wedding',
    ogType: 'article',
    jsonLd: [
      articleJsonLd('Who Gets a Plus-One at Your Wedding? Clear Rules', '2026-09-03', 'Vow Editorial Team', '/blog/who-gets-a-plus-one-wedding'),
      breadcrumb([{ name: 'Home', url: '/' }, { name: 'Blog', url: '/blog' }, { name: 'Plus-One Rules', url: '/blog/who-gets-a-plus-one-wedding' }]),
    ],
    priority: 0.6,
    changefreq: 'monthly',
  },
  '/blog/over-wedding-budget-what-to-cut': {
    title: 'Over Your Wedding Budget? What to Cut, In Order',
    description: 'You have already signed the venue. Here is what can still be cut, ranked by dollars saved per unit of regret, plus what to never cut.',
    canonical: '/blog/over-wedding-budget-what-to-cut',
    ogType: 'article',
    jsonLd: [
      articleJsonLd('Over Your Wedding Budget? What to Cut, In Order', '2026-09-04', 'Vow Editorial Team', '/blog/over-wedding-budget-what-to-cut'),
      breadcrumb([{ name: 'Home', url: '/' }, { name: 'Blog', url: '/blog' }, { name: 'What to Cut When Over Budget', url: '/blog/over-wedding-budget-what-to-cut' }]),
    ],
    priority: 0.6,
    changefreq: 'monthly',
  },
  '/blog/adults-only-wedding-how-to-tell-guests': {
    title: 'How to Tell Guests Your Wedding Is Adults-Only',
    description: 'Where the no-kids message belongs (not the invitation), exact wording that works, and scripts for the relatives who push back anyway.',
    canonical: '/blog/adults-only-wedding-how-to-tell-guests',
    ogType: 'article',
    jsonLd: [
      articleJsonLd('How to Tell Guests Your Wedding Is Adults-Only', '2026-09-05', 'Vow Editorial Team', '/blog/adults-only-wedding-how-to-tell-guests'),
      breadcrumb([{ name: 'Home', url: '/' }, { name: 'Blog', url: '/blog' }, { name: 'Adults-Only Wedding', url: '/blog/adults-only-wedding-how-to-tell-guests' }]),
    ],
    priority: 0.6,
    changefreq: 'monthly',
  },
  '/blog/what-to-book-first-after-engaged': {
    title: 'What to Book First After Getting Engaged (Real Order)',
    description: 'The booking order that prevents expensive backtracking — what must be decided before the venue, and what genuinely can wait six months.',
    canonical: '/blog/what-to-book-first-after-engaged',
    ogType: 'article',
    jsonLd: [
      articleJsonLd('What to Book First After Getting Engaged (Real Order)', '2026-09-06', 'Vow Editorial Team', '/blog/what-to-book-first-after-engaged'),
      breadcrumb([{ name: 'Home', url: '/' }, { name: 'Blog', url: '/blog' }, { name: 'What to Book First', url: '/blog/what-to-book-first-after-engaged' }]),
    ],
    priority: 0.6,
    changefreq: 'monthly',
  },
  '/blog/wedding-shuttle-schedule-guests': {
    title: 'How to Plan a Wedding Shuttle Schedule for Guests',
    description: 'Departure times, how many runs you need, vehicle sizing and real cost per guest — plus the end-of-night return couples always underestimate.',
    canonical: '/blog/wedding-shuttle-schedule-guests',
    ogType: 'article',
    jsonLd: [
      articleJsonLd('How to Plan a Wedding Shuttle Schedule for Guests', '2026-09-07', 'Vow Editorial Team', '/blog/wedding-shuttle-schedule-guests'),
      breadcrumb([{ name: 'Home', url: '/' }, { name: 'Blog', url: '/blog' }, { name: 'Shuttle Schedule', url: '/blog/wedding-shuttle-schedule-guests' }]),
    ],
    priority: 0.6,
    changefreq: 'monthly',
  },
  '/features/budget-tracker': {
    title: 'Wedding Budget Tracker — Track Expenses | Vow',
    description: 'Track every wedding expense by category, log deposits, and see your balance due. Free budget tracker with visual breakdown.',
    canonical: '/features/budget-tracker',
    ogType: 'website',
    jsonLd: breadcrumb([{ name: 'Home', url: '/' }, { name: 'Budget Tracker', url: '/features/budget-tracker' }]),
    priority: 0.7,
    changefreq: 'monthly',
  },
  '/features/guest-list': {
    title: 'Wedding Guest List Manager & RSVP Tracker | Vow',
    description: 'Manage your guest list with RSVP tracking, meal preferences, plus-ones, and invite tracking — all in one organized place.',
    canonical: '/features/guest-list',
    ogType: 'website',
    jsonLd: breadcrumb([{ name: 'Home', url: '/' }, { name: 'Guest List', url: '/features/guest-list' }]),
    priority: 0.7,
    changefreq: 'monthly',
  },
  '/features/checklist': {
    title: 'Wedding Checklist App — 48 Tasks by Date | Vow',
    description: '48 pre-loaded wedding planning tasks organized across 10 timeframes. Check them off, add custom tasks, and track your progress.',
    canonical: '/features/checklist',
    ogType: 'website',
    jsonLd: breadcrumb([{ name: 'Home', url: '/' }, { name: 'Checklist', url: '/features/checklist' }]),
    priority: 0.7,
    changefreq: 'monthly',
  },
  '/features/seating-chart': {
    title: 'Wedding Seating Chart Builder — Drag & Drop | Vow',
    description: 'Create named tables with capacity limits and assign confirmed guests with one click. Visual seating chart for your reception.',
    canonical: '/features/seating-chart',
    ogType: 'website',
    jsonLd: breadcrumb([{ name: 'Home', url: '/' }, { name: 'Seating Chart', url: '/features/seating-chart' }]),
    priority: 0.7,
    changefreq: 'monthly',
  },
  '/tools/wedding-budget-calculator': {
    title: 'Free Wedding Budget Calculator | Vow',
    description: 'Enter your total budget and guest count to get an instant breakdown by category — venue, catering, photography, and more.',
    canonical: '/tools/wedding-budget-calculator',
    ogType: 'website',
    jsonLd: {
      '@context': 'https://schema.org',
      '@type': 'WebApplication',
      name: 'Wedding Budget Calculator',
      url: `${SITE_URL}/tools/wedding-budget-calculator`,
      applicationCategory: 'CalculatorApplication',
      operatingSystem: 'Web',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    },
    priority: 0.8,
    changefreq: 'monthly',
  },
  '/tools/wedding-checklist': {
    title: 'Free Printable Wedding Checklist by Month | Vow',
    description: '48 wedding planning tasks organized by timeframe from 18 months out to your wedding day. Check them off and save your progress.',
    canonical: '/tools/wedding-checklist',
    ogType: 'website',
    jsonLd: {
      '@context': 'https://schema.org',
      '@type': 'WebApplication',
      name: 'Wedding Checklist Tool',
      url: `${SITE_URL}/tools/wedding-checklist`,
      applicationCategory: 'OrganizerApplication',
      operatingSystem: 'Web',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    },
    priority: 0.8,
    changefreq: 'monthly',
  },
  '/login': {
    title: 'Log In — Vow Wedding Planner',
    description: 'Log in to your Vow wedding planning account to access your checklist, budget, guest list, and more.',
    canonical: '/login',
    ogType: 'website',
    noindex: true,
    excludeFromSitemap: true,
    priority: 0.3,
    changefreq: 'monthly',
  },
  '/signup': {
    title: 'Sign Up Free — Vow Wedding Planner',
    description: 'Create your free Vow wedding planning account. Checklist, budget tracker, guest list, and more — no credit card required.',
    canonical: '/signup',
    ogType: 'website',
    noindex: true,
    excludeFromSitemap: true,
    priority: 0.3,
    changefreq: 'monthly',
  },
  '/privacy': {
    title: 'Privacy Policy — Vow Wedding Planner',
    description: 'Privacy Policy for Vow Wedding Planner. Learn how we collect, use, and protect your personal information.',
    canonical: '/privacy',
    ogType: 'website',
    priority: 0.4,
    changefreq: 'yearly',
  },
  '/terms': {
    title: 'Terms of Service — Vow Wedding Planner',
    description: 'Terms of Service for Vow Wedding Planner.',
    canonical: '/terms',
    ogType: 'website',
    priority: 0.4,
    changefreq: 'yearly',
  },
  '/tools/wedding-seating-chart-maker': {
    title: 'Free Wedding Seating Chart Maker — Drag & Drop | Vow',
    description: 'Create your wedding seating chart free. Add named tables, set capacity, assign guests, and print a clean chart for your venue. No account needed.',
    canonical: '/tools/wedding-seating-chart-maker',
    ogType: 'website',
    jsonLd: {
      '@context': 'https://schema.org',
      '@type': 'WebApplication',
      name: 'Wedding Seating Chart Maker',
      url: `${SITE_URL}/tools/wedding-seating-chart-maker`,
      applicationCategory: 'OrganizerApplication',
      operatingSystem: 'Web',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    },
    priority: 0.8,
    changefreq: 'monthly',
  },
  '/tools/wedding-guest-list-template': {
    title: 'Free Wedding Guest List Template — Export CSV | Vow',
    description: 'Build your wedding guest list free. Track names, plus-ones, RSVPs, meal choices, and dietary needs. Export to CSV for your caterer. No account needed.',
    canonical: '/tools/wedding-guest-list-template',
    ogType: 'website',
    jsonLd: {
      '@context': 'https://schema.org',
      '@type': 'WebApplication',
      name: 'Wedding Guest List Template',
      url: `${SITE_URL}/tools/wedding-guest-list-template`,
      applicationCategory: 'OrganizerApplication',
      operatingSystem: 'Web',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    },
    priority: 0.8,
    changefreq: 'monthly',
  },
  '/tools/wedding-day-timeline-template': {
    title: 'Free Wedding Day Timeline Template Generator | Vow',
    description: 'Generate your wedding day timeline from your ceremony time. Get a minute-by-minute schedule from getting ready to last dance. Print or share free.',
    canonical: '/tools/wedding-day-timeline-template',
    ogType: 'website',
    jsonLd: {
      '@context': 'https://schema.org',
      '@type': 'WebApplication',
      name: 'Wedding Day Timeline Template Generator',
      url: `${SITE_URL}/tools/wedding-day-timeline-template`,
      applicationCategory: 'OrganizerApplication',
      operatingSystem: 'Web',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    },
    priority: 0.8,
    changefreq: 'monthly',
  },
  '/tools/wedding-hashtag-generator': {
    title: 'Free Wedding Hashtag Generator | Vow',
    description: 'Generate creative wedding hashtag ideas from your names. Get dozens of options in seconds — punny, classic, rhyming, and more. Free, no account needed.',
    canonical: '/tools/wedding-hashtag-generator',
    ogType: 'website',
    jsonLd: {
      '@context': 'https://schema.org',
      '@type': 'WebApplication',
      name: 'Wedding Hashtag Generator',
      url: `${SITE_URL}/tools/wedding-hashtag-generator`,
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    },
    priority: 0.8,
    changefreq: 'monthly',
  },
  '/tools/honeymoon-budget-calculator': {
    title: 'Free Honeymoon Budget Calculator | Vow',
    description: 'Plan your honeymoon budget. Enter your total and get an instant breakdown by flights, hotels, food, activities, and more. Free, no account needed.',
    canonical: '/tools/honeymoon-budget-calculator',
    ogType: 'website',
    jsonLd: {
      '@context': 'https://schema.org',
      '@type': 'WebApplication',
      name: 'Honeymoon Budget Calculator',
      url: `${SITE_URL}/tools/honeymoon-budget-calculator`,
      applicationCategory: 'CalculatorApplication',
      operatingSystem: 'Web',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    },
    priority: 0.8,
    changefreq: 'monthly',
  },
  '/tools/wedding-vendor-questions': {
    title: 'Wedding Vendor Questions Checklist — Ask Before Booking | Vow',
    description: 'The essential questions to ask every wedding vendor before signing. Photographers, caterers, florists, DJs, and venues — get the full list free.',
    canonical: '/tools/wedding-vendor-questions',
    ogType: 'website',
    jsonLd: {
      '@context': 'https://schema.org',
      '@type': 'WebApplication',
      name: 'Wedding Vendor Questions Checklist',
      url: `${SITE_URL}/tools/wedding-vendor-questions`,
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    },
    priority: 0.8,
    changefreq: 'monthly',
  },
  '/tools/save-the-date-wording': {
    title: 'Free Save the Date Wording Templates & Examples | Vow',
    description: 'Copy-paste save the date wording for every style — formal, casual, destination, LGBTQ+, and more. Free templates, no account needed.',
    canonical: '/tools/save-the-date-wording',
    ogType: 'website',
    jsonLd: {
      '@context': 'https://schema.org',
      '@type': 'WebApplication',
      name: 'Save the Date Wording Generator',
      url: `${SITE_URL}/tools/save-the-date-wording`,
      applicationCategory: 'UtilityApplication',
      operatingSystem: 'Web',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    },
    priority: 0.8,
    changefreq: 'monthly',
  },
};

export function getSeoForPath(pathname: string): RouteSeo | undefined {
  return ROUTE_SEO[pathname];
}

export const SITE_URL_EXPORT = SITE_URL;
export { DEFAULT_OG, faqJsonLd };
